CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(100) NOT NULL DEFAULT '',
  role VARCHAR(30) NOT NULL DEFAULT 'viewer',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS company (
  id INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  name VARCHAR(200) NOT NULL DEFAULT '',
  name_en VARCHAR(200) NOT NULL DEFAULT '',
  phone VARCHAR(50) NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  taxno VARCHAR(50) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS app_seq (
  id INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  emp INT NOT NULL DEFAULT 0,
  htr INT NOT NULL DEFAULT 0,
  vac INT NOT NULL DEFAULT 0,
  prod INT NOT NULL DEFAULT 0,
  mov INT NOT NULL DEFAULT 0,
  quote INT NOT NULL DEFAULT 78
);

CREATE TABLE IF NOT EXISTS app_settings (
  id INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  quote_default_terms JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS employees (
  id VARCHAR(10) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(30) NOT NULL DEFAULT '',
  salary NUMERIC(12, 2) NOT NULL DEFAULT 0,
  opening NUMERIC(12, 2) NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS htrans (
  id VARCHAR(20) PRIMARY KEY,
  emp_id VARCHAR(10) NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  date DATE,
  type VARCHAR(20) NOT NULL,
  amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  hours NUMERIC(8, 2),
  desc_text TEXT NOT NULL DEFAULT '',
  paid BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS vacations (
  id VARCHAR(20) PRIMARY KEY,
  emp_id VARCHAR(10) NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  from_date DATE NOT NULL,
  to_date DATE NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  settled BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS products (
  id VARCHAR(10) PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  open_prod NUMERIC(12, 2) NOT NULL DEFAULT 0,
  open_draw NUMERIC(12, 2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS moves (
  id VARCHAR(20) PRIMARY KEY,
  prod_id VARCHAR(10) NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  date DATE,
  type VARCHAR(10) NOT NULL,
  qty NUMERIC(12, 2) NOT NULL DEFAULT 0,
  desc_text TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_htrans_emp ON htrans(emp_id);
CREATE INDEX IF NOT EXISTS idx_vacations_emp ON vacations(emp_id);
CREATE INDEX IF NOT EXISTS idx_moves_prod ON moves(prod_id);

CREATE TABLE IF NOT EXISTS quotes (
  quote_number INT PRIMARY KEY,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  saved_at TIMESTAMPTZ,
  saved_by VARCHAR(50) NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_quotes_saved_at ON quotes(saved_at DESC);
